FROM python:3.10-slim

WORKDIR /app

COPY realtime_dashboard.py /app/realtime_dashboard.py
COPY message_store.py /app/message_store.py

RUN pip install --no-cache-dir streamlit kafka-python

EXPOSE 8501

CMD ["streamlit", "run", "realtime_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
